### ISSUE TITLE
jsontogenbank error

### ISSUE THREAD

**Issue by hotblast** [TeselaGen/ve-sequence-parsers#16]
@tnrich 
First I saved the module of jsontogenbank as json2gbk.js 
https://github.com/TeselaGen/ve-sequence-parsers#jsontogenbank-same-interface-as-jsontofasta-no-async-required
 
 node json2gbk.js 
Then I launch the program, I got following errors.

/panfs/biopan01/scratch-147760/147760/BH_data/json2gbk.js:4
const jsonToGenbank = require('bio-parsers/parsers/jsonToGenbank');
                                                                 ^
 
SyntaxError: Identifier 'jsonToGenbank' has already been declared
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

**Comment by tnrich** [comment]
@hotblast hey there! Are you using a linter on your JS code? Maybe you've got jsonToGenbank declared somewhere else in the file already? 

I would also recommend using the module directly from NPM, not manually saving the file. 

I could pair with you sometime if you'd like?

**Comment by tnrich** [comment]
Closing for now @hotblast . Please get in touch if you need help
